[package]
name = "gruik-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock", "serde"] }
duration-str = { version = "0.5.1" }
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
serde_yaml = "0.9.25"
sha2 = "0.10.7"
loirc = "0.2.0"
encoding = "0.2.33"
feed-rs = "1.3"
ureq = "2.7.1"

[profile.release]
strip=true